on:
  push:
    tags: "v*"
  release:
    types: [published]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - id: foo
        uses: yougellysjelly/myactions/echo-action@v5
        with:
          who-to-greet: $GITHUB_REPOSITORY
          repository-to-clone: $GITHUB_REPOSITORY
          tag-to-checkout: ${{ steps.get_tag_name.outputs.VERSION }}
