on:
  push:
    tags: "v*"
  release:
    types: [published]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Get repo details
        id: get_repo_details
        run: |
          echo ::set-output name=OWNER::${GITHUB_REPOSITORY/\/*/}
          echo ::set-output name=REPO::${GITHUB_REPOSITORY/*\//}
      - id: foo
        uses: yougellysjelly/myactions/echo-action@v7
        with:
          who-to-greet: ${{ format('{0}/{1}', steps.get_repo_details.outputs.OWNER, steps.get_repo_details.outputs.REPO) }}
          repository-to-clone: ${{ format('{0}/{1}', steps.get_repo_details.outputs.OWNER, steps.get_repo_details.outputs.REPO) }}
          tag-to-checkout: ${{ steps.get_tag_name.outputs.VERSION }}
